import type { Metadata } from "next";
import {Roboto} from "next/font/google";
import "./globals.css";
import {AppWrapper} from '@/context'

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-rooto",
  weight: ["100", "300", "400", "500", "700", "900"],
});

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Fronted explore",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={roboto.className}
      >
        <AppWrapper>
        {children}
        </AppWrapper>
      </body>
    </html>
  );
}
